/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdbce",
        "on-background": "#231a0d",
        "surface-dim": "#e9d7c1",
        "surface-tint": "#a83900",
        "on-tertiary-container": "#f4fff2",
        "on-surface": "#231a0d",
        "primary-fixed-dim": "#ffb59a",
        "on-surface-variant": "#594139",
        "primary-container": "#c84b0f",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#87d89b",
        "secondary": "#3f5f92",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "outline": "#8c7167",
        "on-tertiary-fixed": "#00210c",
        "on-secondary-fixed": "#001b3d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#380d00",
        "surface-container": "#fdebd5",
        "error": "#ba1a1a",
        "surface-bright": "#fff8f3",
        "on-primary-fixed-variant": "#802a00",
        "secondary-fixed-dim": "#a9c7ff",
        "outline-variant": "#e0bfb4",
        "secondary-container": "#a5c5fe",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#254778",
        "tertiary-container": "#33834f",
        "inverse-on-surface": "#ffeeda",
        "surface": "#fff8f3",
        "surface-container-low": "#fff2e2",
        "background": "#fff8f3",
        "inverse-primary": "#ffb59a",
        "inverse-surface": "#392f20",
        "on-tertiary-fixed-variant": "#005228",
        "tertiary-fixed": "#a3f5b5",
        "surface-variant": "#f2e0ca",
        "primary": "#a23700",
        "tertiary": "#136938",
        "surface-container-highest": "#f2e0ca",
        "on-primary-container": "#fffaf9",
        "surface-container-high": "#f7e6cf",
        "on-primary": "#ffffff",
        "on-secondary-container": "#315183",
        "secondary-fixed": "#d6e3ff",
        "archival-primary": "#a23700",
        "archival-secondary": "#c84b0f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "monospace"],
        "mono": ["Space Grotesk", "monospace"],
      }
    },
  },
  plugins: [],
}
