export const generateReport = (user, analytics) => {
    const { metrics, insights, growthScore } = analytics;
    
    if (!user || !metrics) return;

    const reportText = `
==============================================
      GROWTH INTELLIGENCE REPORT
==============================================
Date: ${new Date().toLocaleDateString()}
User: ${user.name || 'Learner'}
Role: ${user.role || 'User'}

--- OVERVIEW START ---
Growth Score: ${growthScore} / 100
Modules Completed: ${metrics.totalModulesCompleted}
Completion Rate: ${metrics.completionRate}%
Active Streak: ${metrics.activeStreak} days
Time Spent Learning: ~${metrics.timeSpentLearning} hours
Mentor Interactions: ${metrics.mentorInteractions}
--- OVERVIEW END ---

--- AI INSIGHTS ---
${insights.map((insight, i) => `${i + 1}. [${insight.type.toUpperCase()}] ${insight.text}`).join('\n')}

--- RECOMMENDATIONS ---
- Maintain your active streak.
- Continue engaging with the mentor on complex topics.
- Complete active modules before beginning new ones.

==============================================
Generated by PassionPath Analytics
==============================================
    `;

    // Create a Blob and trigger download
    const blob = new Blob([reportText.trim()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(user.name || 'User').replace(/\s+/g, '_')}_Growth_Report.txt`;
    
    // Fallback for older browsers or if body append is needed
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    
    URL.revokeObjectURL(url);
};
